# Generated by Django 4.2.6 on 2023-11-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date_course',
            name='date',
            field=models.DateField(),
        ),
    ]
