# Generated by Django 4.2.6 on 2023-11-08 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_students_image_example'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='static/images/students/<django.db.models.fields.CharField>')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.students')),
            ],
        ),
        migrations.DeleteModel(
            name='example',
        ),
    ]
