# Generated by Django 4.2.6 on 2023-11-08 19:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentimages_delete_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentimages',
            name='image',
            field=models.ImageField(upload_to=core.models.file_path),
        ),
    ]
