# Generated by Django 4.2.6 on 2023-11-08 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=100)),
                ('prof_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(blank=None, max_length=1000)),
                ('rollNumber', models.CharField(blank=None, max_length=100)),
                ('image', models.ImageField(upload_to='static/images/students/<django.db.models.fields.CharField>')),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_mark', models.CharField(choices=[('present', '1'), ('absent', '0')], default='absent', max_length=20)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.class')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.date')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.students')),
            ],
        ),
    ]
